TOPDIR = ../..

include $(TOPDIR)/Preamble.make

DIST_FILES = filecheck_test_run.sh inode_block_test.sh verify_utils.sh

BIN_EXTRA = filecheck_test_run.sh inode_block_test.sh verify_utils.sh

include $(TOPDIR)/Postamble.make


